
# Sovelluksen nimi ja portti
spring.application.name=core-ledger-api
server.port=8080

# H2-tietokannan konfiguraatio (In-Memory)
spring.datasource.url=jdbc:h2:mem:ledgerdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Selainkonsolin aktivointi (Käytettävissä osoitteessa http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# JPA / Hibernate -asetukset
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Luo ja päivittää tietokantataulut automaattisesti domain-entiteettien mukaan
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

